# Generated by Django 2.2.1 on 2020-06-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='messege_html',
            new_name='message_html',
        ),
    ]
